site_name: 纯爱合集
theme:
  name: material
  language: "zh"

nav:
  - 主页: index.md
  - 2023年:
      - 希望我孩子的爱情不参杂一点金钱: 2023/20230117_希望我孩子的爱情不参杂一点金钱/index.md
  - 2021年:
      - 你还记得我是你女朋友啊: 2021/20211202_你还记得我是你女朋友啊/index.md
